insert into event (organization_id, name, description, contact, email, application_url, location, zip_code, time, size, length) values
  (2, 'Cat Care Volunteer', 'We are in need of cat-savvy people to help cats at our Petco adoption center at 991 Second Avenue between 52nd & 53rd Streets in Manhattan. It means cleaning cages and feeding the cats; you can always spend some fun time with them once the chores are done :-). For the Saturday evening shift, folks need to arrive at 5:45pm to begin their cat care shift. Familiarity with felines and a sense of responsibility are required, as well as the ability to commit to about 1+ hour a week for this shift for at least 6 months, i.e., including this summer. Some physical strength and agility are required by the role, including the ability to reach the back of the cages to clean and to safely maneuver around a cat while the cat stays in the cage when you are cleaning. Because volunteers provide food & water to the cats and create a clean environment for them during their shift, reliability is a MUST. You must be 18 years of age or older. Please read, date, sign, and then submit the Volunteer Application that will be attached as a PDF when you get the reply email message. A PDF of the volunteer flyer will also be attached. Thank you.', '', '', '',
      '991 Second Avenue', '10022',
      TIMESTAMP '2017-11-20 15:00:00', 30, 60),
  (3, 'Drive a leg – Save a life!', 'Simply by using your vehicle you can save animals -Volunteer your time to transport animals along what is called a "Rescue Relay Transport". Each week there arehundreds of animal rescue transports taking place where animals are moved from high-kill shelters to no-kill shelters and rescue organizations, as well as foster homes and adopters. It''s easy for you to get involved and help save more animals simply by driving a leg in this relay.', '', '', '',
      'New York, NY', '10162',
      TIMESTAMP '2017-11-20 13:00:00', 25, 90),
  (4, 'Kitchen Prep', 'Help the GMHC kitchen staff in set up, prepare foods, and clean up the kitchen for hundreds of HIV/Aids affected individuals in need.', '', '', '',
      'Hell''s Kitchen', '10023',
      TIMESTAMP '2017-11-20 17:00:00', 30, 105),
  (5, 'Deliver with Carter Burden', 'Deliver lunches on foot to seniors participating in the Meals on Wheels program.', '', '', '',
      'Lenox Hill', '10021',
      TIMESTAMP '2017-11-20 8:00:00', 34, 110),
  (4, 'Lunch Meal Service', 'Help provide nutritious homemade meals to HIV/AIDS affected individuals as part of the GMHC community. Volunteers will serve food,...', '', '', '',
      'Hell''s Kitchen', '10023',
      TIMESTAMP '2017-11-20 11:00:00', 28, 90),
  (6, 'Casino Game Night', 'Help escort the residents to and from Casino Game Night, facilitate games and have a fun filled evening of socializing and exciting games!', '', '', '',
      'Upper West Side', '10023',
      TIMESTAMP '2017-11-20 10:00:00', 38, 45),
  (7, 'Blankets of Love with AHRC', 'Create knitted and crocheted squares that will be made into blankets alongside AHRC volunteers. Participants may also create hats,...', '', '', '',
      'Greenwich Village', '10023',
      TIMESTAMP '2017-11-22 14:00:00', 35, 145),
  (6, 'Afternoon Fun', 'Join the the elders of the New Jewish Home in their Wednesday afternoon activities. Volunteers will transport seniors to and from the...', '', '', '',
      'Upper West Side', '10023',
      TIMESTAMP '2017-11-22 15:00:00', 25, 75),
  (6, 'Concert', 'Enjoy a concert and socialize with seniors at The New Jewish Home. Volunteers will help transport residents from their floor to the...', '', '', '',
      'Upper West Side', '10023',
      TIMESTAMP '2017-11-22 16:00:00', 40, 65),
  (6, 'Creative Writing with Seniors', 'Empower residents of the New Jewish Home by transporting 40-45 seniors to the auditorium, and then serve as scribes to help the residents...', '', '', '',
      'Upper West Side', '10023',
      TIMESTAMP '2017-11-24 14:00:00', 39, 145),
  (5, 'Deliver with Carter Burden', 'Deliver lunches on foot to seniors participating in the Meals on Wheels program.', '', '', '',
      'Lenox Hill', '10021',
      TIMESTAMP '2017-11-27 11:00:00', 38, 100),
  (4, 'Lunch Meal Service', 'Help provide nutritious homemade meals to HIV/AIDS affected individuals as part of the GMHC community. Volunteers will serve food,...', '', '', '',
      'Hell''s Kitchen', '10023',
      TIMESTAMP '2017-11-27 17:00:00', 23, 50),
  (6, 'Casino Game Night', 'Help escort the residents to and from Casino Game Night, facilitate games and have a fun filled evening of socializing and exciting games!', '', '', '',
      'Upper West Side', '10023',
      TIMESTAMP '2017-11-27 16:00:00', 30, 85),
  (8, 'Activity Time with the Dementia Ward', 'Interact with residents of the dementia ward at a nursing home through trivia games, singing, reading and assisting with snack time....', '', '', '',
      'Washington Heights', '10031',
      TIMESTAMP '2017-11-27 15:00:00', 25, 105),
  (9, 'Pantry Preparation', 'Help prepare this Client Choice Pantry by assisting with produce shipment intake, and pantry organization and setup. Tasks will be...', '', '', '',
      'Greenwich Village', '10012',
      TIMESTAMP '2017-11-28 10:00:00', 36, 90),
  (6, 'Beauty Spa', 'Give special attention to the residents of the New Jewish Home. Spend this project painting the nails of residents and socializing.', '', '', '',
      'Upper West Side', '10023',
      TIMESTAMP '2017-11-28 18:00:00', 24, 115),
  (4, 'Lunch Meal Service', 'Help provide nutritious homemade meals to HIV/AIDS affected individuals as part of the GMHC community. Volunteers will serve food,...', '', '', '',
      'Hell''s Kitchen', '10023',
      TIMESTAMP '2017-11-29 13:00:00', 40, 150),
  (4, 'Early Dinner Meal Service', 'Feed hundreds of HIV+ individuals in a daily meal service at GMHC. You''ll serve food, hand out trays/utensils, clear tables and clean up...', '', '', '',
      'Hell''s Kitchen', '10023',
      TIMESTAMP '2017-12-08 15:00:00', 28, 70),
  (15, 'Breakfast at Crossroads', 'Set up for and serve hot meals to over 200 homeless and hungry women and men. Volunteers should make sure to be on time for this early...', '', '', '',
       'Turtle Bay/Sutton Place', '10021',
      TIMESTAMP '2017-12-11 17:00:00', 40, 45),
  (4, 'Kitchen Prep', 'Help the GMHC kitchen staff in set up, prepare foods, and clean up the kitchen for hundreds of HIV/Aids affected individuals in need....', '', '', '',
      'Hell''s Kitchen', '10023',
      TIMESTAMP '2017-12-11 16:00:00', 34, 55),
  (5, 'Deliver with Carter Burden', 'Deliver lunches on foot to seniors participating in the Meals on Wheels program.', '', '', '',
      'Lenox Hill', '10021',
      TIMESTAMP '2017-12-11 17:00:00', 36, 100),
  (4, 'Lunch Meal Service', 'Help provide nutritious homemade meals to HIV/AIDS affected individuals as part of the GMHC community. Volunteers will serve food,...', '', '', '',
      'Hell''s Kitchen', '10023',
      TIMESTAMP '2017-12-11 13:00:00', 25, 70),
  (6, 'Casino Game Night', 'Help escort the residents to and from Casino Game Night, facilitate games and have a fun filled evening of socializing and exciting games!', '', '', '',
      'Upper West Side', '10023',
      TIMESTAMP '2017-12-11 15:00:00', 23, 115),
  (8, 'Fun and Games', 'Play trivia games and have a blast with the residents of local nursing home to help memory and brain function.', '', '', '',
      'Washington Heights', '10031',
      TIMESTAMP '2017-12-12 15:00:00', 28, 135),
  (9, 'Pantry Preparation', 'Help prepare this Client Choice Pantry by assisting with produce shipment intake, and pantry organization and setup. Tasks will be...', '', '', '',
      'Greenwich Village', '10012',
      TIMESTAMP '2017-12-12 11:00:00', 27, 125);


insert into organization(name, address, email, website) values
('City Critters, Inc.', '', '', ''),
('Pilots to the Rescue', '', '', ''),
('Gay Men''s Health Crisis (GMHC)', '', '', '' ),
('Carter Burden Network', '', '', ''),
('The New Jewish Home', '', '', ''),
('AHRC NYC', '', '', ''),
('Isabella Geriatric Center', '', '', ''),
('U.M The Church of the Village', '', '', ''),
('New York Common Pantry', '', '', ''),
('City Harvest', '', '', ''),
('Food Bank for New York City', '', '', ''),
('Earth Matter NY', '', '', ''),
('Breaking Ground', '', '', ''),
('St. Bartholomew''s Church', '', '', '');


insert into event_interest (event_id, interest_id, last_updated) values
  (3, 1, now()),
  (3, 2, now()),
  (4, 1, now()),
  (4, 4, now()),
  (5, 3, now()),
  (5, 4, now()),
  (5, 7, now()),
  (5, 13, now()),
  (5, 17, now()),
  (6, 4, now()),
  (6, 13, now()),
  (7, 4, now()),
  (7, 13, now()),
  (8, 3, now()),
  (8, 6, now()),
  (8, 17, now()),
  (8, 21, now()),
  (8, 23, now()),
  (9, 3, now()),
  (9, 6, now()),
  (9, 11, now()),
  (9, 15, now()),
  (10, 5, now()),
  (10, 6, now()),
  (10, 23, now()),
  (11, 2, now()),
  (11, 3, now()),
  (11, 6, now()),
  (11, 23, now()),
  (12, 3, now()),
  (12, 5, now()),
  (12, 6, now()),
  (12, 23, now()),
  (13, 4, now()),
  (13, 5, now()),
  (13, 13, now()),
  (14, 3, now()),
  (14, 4, now()),
  (14, 13, now()),
  (15, 3, now()),
  (15, 6, now()),
  (15, 17, now()),
  (15, 21, now()),
  (15, 23, now()),
  (16, 4, now()),
  (16, 6, now()),
  (17, 11, now()),
  (17, 13, now()),
  (18, 6, now()),
  (18, 15, now()),
  (19, 4, now()),
  (19, 13, now()),
  (20, 4, now()),
  (20, 13, now()),
  (21, 4, now()),
  (21, 13, now()),
  (22, 4, now()),
  (22, 13, now()),
  (23, 4, now()),
  (23, 13, now()),
  (24, 4, now()),
  (24, 13, now()),
  (25, 3, now()),
  (25, 6, now()),
  (25, 17, now()),
  (25, 21, now()),
  (25, 23, now()),
  (26, 4, now()),
  (26, 6, now()),
  (26, 21, now()),
  (27, 11, now()),
  (27, 23, now());


